import type { Metadata } from "next";
import "../globals.css";
import { Header } from "../components/Header";
import { SearchProvider } from "@/context/SearchContext/SearchContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <SearchProvider>
        <Header />
        {children}
      </SearchProvider>
    </main>
  );
}
